package Entiteti;
// Generated Aug 18, 2016 3:29:18 AM by Hibernate Tools 4.3.1



/**
 * Magacin generated by hbm2java
 */
public class Magacin  implements java.io.Serializable {


     private Integer id;
     private int idPica;
     private String naziv;
     private int kolicina;

    public Magacin() {
    }

    public Magacin(int idPica, String naziv, int kolicina) {
       this.idPica = idPica;
       this.naziv = naziv;
       this.kolicina = kolicina;
    }
    public Magacin(Artikal a)
    {
        this.idPica = a.getTip();
        this.naziv = a.getNaziv();
        this.kolicina = 0;
    }
    public Magacin(Magacin m)
    {
        this.idPica = m.idPica;
        this.kolicina = m.kolicina;
        this.naziv = m.naziv;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdPica() {
        return this.idPica;
    }
    
    public void setIdPica(int idPica) {
        this.idPica = idPica;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }

    @Override
    public String toString() {
        return "Magacin{" + "id=" + id + ", idPica=" + idPica + ", naziv=" + naziv + ", kolicina=" + kolicina + '}';
    }




}


